### ISSUE TITLE
Volume de données?

### ISSUE THREAD

**Issue by taspoff** [ChrisCB65/swade-une-aventure-dun-autre-age#1]
download super lent depuis OVH.... T'as un volume de données de combien??? :)
Fabien

**Comment by ChrisCB65** [comment]
Salut, 

En fait, j'ai rien optimisé pour l'instant, il y a beaucoup de doublons. Je ne m'en sers que pour faire les mises à jours entre mes tables (2 licences > 2 instances). J'aurais voulu le garder en privé mais je ne sais pas comment faire pour que Foundry y accède. En gros, c'est pas utilisable encore.

**Comment by ChrisCB65** [comment]
> download super lent depuis OVH.... T'as un volume de données de combien??? :) Fabien

Mais j'ai pas répondu à la question. Le module est censé faire 252Mo.
